version: '2'

services:
  company:
    image: 'bitnami/symfony:1'
    ports:
      - '8000:8000'
    volumes:
      - '.:/app/company'
    environment:
      - SYMFONY_PROJECT_NAME=company
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=notroot
      - MARIADB_PASSWORD=pwd
      - MARIADB_DATABASE=listing
    depends_on:
      - mariadb
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=notroot
      - MARIADB_PASSWORD=pwd
      - MARIADB_DATABASE=listing
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_PORT=3306