<?php

namespace App\DataFixtures;

use App\Entity\LegalForm;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Faker;

class LegalFormFixtures extends Fixture
{
    public function load(ObjectManager $manager)
    {
        $faker = Faker\Factory::create();
        $legalFormType = array(
                "Entrepreneur individuel",
                "Groupement de droit privé non doté de la personnalité morale",
                "Indivision",
                "Indivision entre personnes physiques",
                "Indivision avec personne morale",
                "Société créée de fait",
                "Société créée de fait entre personnes physiques",
                "Société créée de fait avec personne morale",
                "Société en participation",
                "Société en participation entre personnes physiques",
                "Société en participation avec personne morale",
                "Société en participation de professions libérales",
                "Fiducie",
                "Paroisse hors zone concordataire",
                "Autre groupement de droit privé non doté de la personnalité morale",
                "Personne morale de droit étranger",
                "Personne morale de droit étranger, immatriculée au RCS (registre du commerce et des
                sociétés)",
                "Représentation ou agence commerciale d'état ou organisme public étranger immatriculé au
                RCS",
                "Société commerciale étrangère immatriculée au RCS",
                "Personne morale de droit étranger, non immatriculée au RCS",
                "Organisation internationale",
                "État, collectivité ou établissement public étranger",
                "Société étrangère non immatriculée au RCS",
                "Autre personne morale de droit étranger",
                "Personne morale de droit public soumise au droit commercial",
                "Etablissement public ou régie à caractère industriel ou commercial",
                "Établissement public national à caractère industriel ou commercial doté d'un comptable
                public",
                "Établissement public national à caractère industriel ou commercial non doté d'un comptable
                public",
                "Exploitant public",
                "Établissement public local à caractère industriel ou commercial",
                "Régie d'une collectivité locale à caractère industriel ou commercial",
                "Institution Banque de France",
                "Société commerciale",
                "Société coopérative commerciale particulière",
                "Société de caution mutuelle",
                "Société coopérative de banque populaire",
                "Caisse de crédit maritime mutuel",
                "Caisse (fédérale) de crédit mutuel",
                "Association coopérative inscrite (droit local Alsace Moselle)",
                "Caisse d'épargne et de prévoyance à forme coopérative",
                "Société en Nom Collectif",
                "Société en nom collectif coopérative",
                "Société en commandite",
                "Société en commandite simple",
                "Société en commandite simple coopérative",
                "Société en Commandite par Actions",
                "Société en commandite par actions coopérative",
                "Société de Participations Financières de Profession Libérale Société en commandite par
                actions (SPFPL SCA)",
                "Société d'exercice libéral en commandite par actions",
                "Société à Responsabilité Limitée",
                "SARL nationale",
                "SARL d'économie mixte",
                "SARL immobilière pour le commerce et l'industrie (SICOMI)",
                "SARL immobilière de gestion",
                "SARL d'aménagement foncier et d'équipement rural (SAFER)",
                "SARL mixte d'intérêt agricole (SMIA)",
                "SARL d'intérêt collectif agricole (SICA)",
                "SARL d'attribution",
                "SARL coopérative de construction",
                "SARL coopérative de consommation",
                "SARL coopérative artisanale",
                "SARL coopérative d'intérêt maritime",
                "SARL coopérative de transport",
                "SARL coopérative ouvrière de production (SCOP)",
                "Société à responsabilité limitée (sans autre indication)",
                "Société Anonyme",
                "SA à participation ouvrière à conseil d'administration",
                "SA nationale à conseil d'administration",
                "SA d'économie mixte à conseil d'administration",
                "Société d'investissement à capital variable (SICAV) à conseil d'administration",
                "SA immobilière pour le commerce et l'industrie (SICOMI) à conseil d'administration",
                "SA immobilière d'investissement à conseil d'administration",
                "SA d'aménagement foncier et d'équipement rural (SAFER) à conseil d'administration",
                "Société anonyme mixte d'intérêt agricole (SMIA) à conseil d'administration",
                "SA d'intérêt collectif agricole (SICA) à conseil d'administration",
                "SA d'attribution à conseil d'administration",
                "SA coopérative de production de HLM à conseil d'administration",
                "SA de crédit immobilier à conseil d'administration",
                "SA coopérative de consommation à conseil d'administration",
                "SA coopérative de commerçants-détaillants à conseil d'administration",
                "SA coopérative artisanale à conseil d'administration",
                "SA coopérative (d'intérêt) maritime à conseil d'administration",
                "SA coopérative de transport à conseil d'administration",
                "Société d'exercice libéral à forme anonyme à conseil d'administration",
                "SA à conseil d'administration (s.a.i.)",
                "Société anonyme à directoire",
                "SA à participation ouvrière à directoire",
                "SA nationale à directoire",
                "SA d'économie mixte à directoire",
                "Société d'investissement à capital variable (SICAV) à directoire",
                "SA immobilière pour le commerce et l'industrie (SICOMI) à directoire",
                "SA immobilière d'investissement à directoire",
                "Safer anonyme à directoire",
                "SA mixte d'intérêt agricole (SMIA)",
                "SA d'intérêt collectif agricole (SICA)",
                "SA d'attribution à directoire",
                "SA coopérative de construction à directoire",
                "SA de HLM à directoire",
                "Société coopérative de production de HLM anonyme à directoire",
                "SA de crédit immobilier à directoire",
                "SA coopérative de consommation à directoire",
                "SA coopérative de commerçants-détaillants à directoire",
                "SA coopérative artisanale à directoire",
                "SA coopérative d'intérêt maritime à directoire",
                "SA coopérative de transport à directoire",
                "SA coopérative ouvrière de production (SCOP) à directoire",
                "SA union de sociétés coopératives à directoire",
                "Autre SA coopérative à directoire",
                "Société de Participations Financières de Profession Libérale Société anonyme à Directoire
                (SPFPL SA à directoire)",
                "Société d'exercice libéral à forme anonyme à directoire",
                "SA à directoire (s.a.i.)",
                "Société par Actions Simplifiée",
                "Société par Actions Simplifiée Unipersonnelle",
                "Société de Participations Financières de Profession Libérale Société par actions simplifiée
                (SPFPL SAS)",
                "Société d'exercice libéral par action simplifiée",
                "Société européenne",
                "Autre personne morale immatriculée au RCS",
                "Caisse d'Épargne et de Prévoyance",
                "Groupement d'intérêt économique",
                "Groupement européen d'intérêt économique (GEIE)",
                "Groupement d'intérêt économique (GIE)",
                "Société coopérative agricole",
                "Coopérative d'utilisation de matériel agricole en commun (CUMA)",
                "Société coopérative agricole",
                "Union de sociétés coopératives agricoles",
                "Société d'assurance mutuelle",
               "Société d'assurance à forme mutuelle",
                "Société civile",
                "Sociétés Interprofessionnelles de Soins Ambulatoires",
                "Société civile de placement collectif immobilier (SCPI)",
                "Société civile d'intérêt collectif agricole (SICA)",
                "Groupement Agricole d’Exploitation en Commun",
                "Groupement foncier agricole",
                "Groupement agricole foncier",
                "Groupement forestier",
                "Groupement pastoral",
                "Groupement foncier et rural",
                "Société civile foncière",
                "Société civile immobilière",
                "Société civile immobilière de construction-vente",
                "Société civile d'attribution",
                "Société civile coopérative de construction",
                "Société civile immobilière d' accession progressive à la propriété",
                "Société civile coopérative de consommation",
                "Société civile coopérative d'intérêt maritime",
                "Société civile coopérative entre médecins",
                "Autre société civile coopérative",
                "SCP d'avocats",
                "SCP d'avocats aux conseils",
                "SCP d'avoués d'appel",
                "SCP d'huissiers",
                "SCP de notaires",
                "SCP de commissaires-priseurs",
                "SCP de greffiers de tribunal de commerce",
                "SCP de conseils juridiques",
                "SCP de commissaires aux comptes",
                "SCP de médecins",
                "SCP de dentistes",
                "SCP d'infirmiers",                
                "SCP de masseurs-kinésithérapeutes",
                "SCP de directeurs de laboratoire d'analyse médicale",
                "SCP de vétérinaires",
                "SCP de géomètres experts",
                "SCP d'architectes",
                "Société Civile Professionnelle",
                "Société civile laitière",
                "Société civile de moyens",
                "Caisse locale de crédit mutuel",
                "Caisse de crédit agricole mutuel",
                "Société Civile d'Exploitation Agricole",
                "Exploitation Agricole à Responsabilité Limitée",
                "Autre société civile",
                "Autre personne morale de droit privé inscrite au registre du commerce et des sociétés",
                "Autre personne de droit privé inscrite au registre du commerce et des sociétés",
                "Personne morale et organisme soumis au droit administratif",
                "Administration de l'état",
                "Autorité constitutionnelle",
                "Autorité administrative indépendante",
                "Ministère",
                "Service central d'un ministère",
                "Service du ministère de la Défense",
                "Service déconcentré à compétence nationale d'un ministère (hors Défense)",
                "Service déconcentré de l'État à compétence (inter) régionale",
                "Service déconcentré de l'État à compétence (inter) départementale",
                "(Autre) Service déconcentré de l'État à compétence territoriale",
                "Ecole nationale non dotée de la personnalité morale",
                "Collectivité territoriale",
                "Commune et commune nouvelle",
                "Département",
                "Collectivité et territoire d'Outre Mer",
                "(Autre) Collectivité territoriale",
                "Région",
                "Etablissement public administratif",
                "Commune associée et commune déléguée",
                "Section de commune",
                "Ensemble urbain",
                "Association syndicale autorisée",
                "Association foncière urbaine",
                "Association foncière de remembrement",
                "Établissement public local d'enseignement",
                "Pôle métropolitain",
                "Secteur de commune",
                "District urbain",
                "Communauté urbaine",
                "Métropole",
                "Syndicat intercommunal à vocation multiple (SIVOM)",
                "Communauté de communes",
                "Communauté de villes",
                "Communauté d'agglomération",
                "Autre établissement public local de coopération non spécialisé ou entente",
                "Institution interdépartementale ou entente",
                "Institution interrégionale ou entente",
                "Syndicat intercommunal à vocation unique (SIVU)",
                "Syndicat mixte communal",
                "Autre syndicat mixte",
                "Commission syndicale pour la gestion des biens indivis des communes",
                "Centre communal d'action sociale",
                "Caisse des écoles",
                "Caisse de crédit municipal",
                "Établissement d'hospitalisation",
                "Syndicat inter hospitalier",
                "Établissement public local social et médico-social",
                "Office public d'habitation à loyer modéré (OPHLM)",
                "Service départemental d'incendie",
                "Établissement public local culturel",
                "Régie d'une collectivité locale à caractère administratif",
                "(Autre) Établissement public administratif local",
                "Organisme consulaire",
                "Établissement public national ayant fonction d'administration centrale",
                "Établissement public national à caractère scientifique culturel et professionnel",
                "Autre établissement public national d'enseignement",
                "Autre établissement public national administratif à compétence territoriale limitée",
                "Établissement public national à caractère administratif",
                "Autre personne morale de droit public administratif",
                "Groupement d'intérêt public (GIP)",
                "Établissement public des cultes d'Alsace-Lorraine",
                "Etablissement public administratif, cercle et foyer dans les armées",
                "Groupement de coopération sanitaire à gestion publique",
                "Autre personne morale de droit administratif",
                "Organisme privé spécialisé",
                "Organisme gérant un régime de protection sociale à adhésion obligatoire",
                "Régime général de la Sécurité Sociale",
                "Régime spécial de Sécurité Sociale",
                "Institution de retraite complémentaire",
                "Mutualité sociale agricole",
                "Régime maladie des non-salariés non agricoles",
                "Régime vieillesse ne dépendant pas du régime général de la Sécurité Sociale",
                "Régime d'assurance chômage",
                "Autre régime de prévoyance sociale",
                "Organisme mutualiste",
                "Mutuelle",
                "Assurance mutuelle agricole",
                "Autre organisme mutualiste",
                "Comité d'entreprise",
                "Comité central d'entreprise",
                "Comité d'établissement",
                "Organisme professionnel",
                "Syndicat de salariés",
                "Syndicat patronal",
                "Ordre professionnel ou assimilé",
                "Centre technique industriel ou comité professionnel du développement économique",
                "Autre organisme professionnel",
                "Organisme de retraite à adhésion non obligatoire",
                "Institution de prévoyance",
                "Institution de retraite supplémentaire",
                "Groupement de droit privé",
                "Syndicat de propriétaires",
                "Syndicat de copropriété",
                "Association syndicale libre",
                "Association",
                "Association non déclarée",
                "Association déclarée",
                "Association déclarée d'insertion par l'économique",
                "Association intermédiaire",
                "Groupement d'employeurs",
                "Association d'avocats à responsabilité professionnelle individuelle",
                "Association déclarée, reconnue d'utilité publique",
                "Congrégation",
                "Association de droit local (Bas-Rhin, Haut-Rhin et Moselle)",
                "Fondation",
                "Autre personne morale de droit privé",
                "Groupement de coopération sanitaire à gestion privée",
        );

        foreach ($legalFormType as $i) {
            $legalForm = new LegalForm;
            $legalForm -> setName($i) ;
            $manager->persist($legalForm);
        }
     

        $manager->flush();
        // $product = new Product();
        // $manager->persist($product);

        $manager->flush();
    }
}
